PLT-1282: add cdap app and env in bucket module (#299)
## 🎫 Ticket

https://jira.cms.gov/browse/PLT-1282

## 🛠 Changes
CDAP env and app added to bucket module variables.tf

## ℹ️ Context

workflow terraform apply failed with is error message
Planning failed. Terraform encountered an error while generating this
plan.

╷
│ Error: Invalid value for variable
│ 
│   on main.tf line 9, in module "tfstate_bucket":
│    9:   app = var.app
│     ├────────────────
│     │ var.app is "cdap"
│ 
│ Valid value for app is ab2d, bcda, or dpc.
│ 
│ This was checked by the validation rule at
│ ../../modules/bucket/variables.tf:4,3-13.
╵
╷
│ Error: Invalid value for variable
│ 
│   on main.tf line 10, in module "tfstate_bucket":
│   10:   env = var.env
│     ├────────────────
│     │ var.env is "mgmt"
│ 
│ Valid value for env is dev, test,sandbox, or prod.
│ 
│ This was checked by the validation rule at
│ ../../modules/bucket/variables.tf:13,3-13.
╵

Error: Process completed with exit code 1.



<!-- If any of the following security implications apply, this PR must
not be merged without Stephen Walter's approval. Explain in this section
and add @SJWalter11 as a reviewer.
  - Adds a new software dependency or dependencies.
  - Modifies or invalidates one or more of our security controls.
  - Stores or transmits data that was not stored or transmitted before.
- Requires additional review of security implications for other reasons.
-->

## 🧪 Validation

see check for cdap-mgmt 
link to successful app cdap and env mgmt run
https://github.com/CMSgov/cdap/actions/runs/17502758868/job/49719410970

---------

Co-authored-by: Maboh Christopher <chris.maboh@aquia.io>