# This is a combination of 25 commits. # This is the 1st commit message:
added tags

# This is the commit message #2:

PLT-1282: Update bucket module to use shared KMS keys (#295)

## 🎫 Ticket

https://jira.cms.gov/browse/PLT-1282

## 🛠 Changes

bucket module was updated to use our shared kms keys

## ℹ️ Context

The bucket module currently creates KMS keys for encrypting and
decrypting tfstate buckets, the is the need to switch to the shared keys
created by the kms-keys service

<!-- If any of the following security implications apply, this PR must
not be merged without Stephen Walter's approval. Explain in this section
and add @SJWalter11 as a reviewer.
  - Adds a new software dependency or dependencies.
  - Modifies or invalidates one or more of our security controls.
  - Stores or transmits data that was not stored or transmitted before.
- Requires additional review of security implications for other reasons.
-->

## 🧪 Validation

See checks

---------

Co-authored-by: Maboh Christopher <chris.maboh@aquia.io>
# This is the commit message #3:

added clusterid

# This is the commit message #4:

remove extra line

# This is the commit message #5:

PLT-1282: add cdap app and env in bucket module (#299)

## 🎫 Ticket

https://jira.cms.gov/browse/PLT-1282

## 🛠 Changes
CDAP env and app added to bucket module variables.tf

## ℹ️ Context

workflow terraform apply failed with is error message
Planning failed. Terraform encountered an error while generating this
plan.

╷
│ Error: Invalid value for variable
│
│   on main.tf line 9, in module "tfstate_bucket":
│    9:   app = var.app
│     ├────────────────
│     │ var.app is "cdap"
│
│ Valid value for app is ab2d, bcda, or dpc.
│
│ This was checked by the validation rule at
│ ../../modules/bucket/variables.tf:4,3-13.
╵
╷
│ Error: Invalid value for variable
│
│   on main.tf line 10, in module "tfstate_bucket":
│   10:   env = var.env
│     ├────────────────
│     │ var.env is "mgmt"
│
│ Valid value for env is dev, test,sandbox, or prod.
│
│ This was checked by the validation rule at
│ ../../modules/bucket/variables.tf:13,3-13.
╵

Error: Process completed with exit code 1.

<!-- If any of the following security implications apply, this PR must
not be merged without Stephen Walter's approval. Explain in this section
and add @SJWalter11 as a reviewer.
  - Adds a new software dependency or dependencies.
  - Modifies or invalidates one or more of our security controls.
  - Stores or transmits data that was not stored or transmitted before.
- Requires additional review of security implications for other reasons.
-->

## 🧪 Validation

see check for cdap-mgmt
link to successful app cdap and env mgmt run
https://github.com/CMSgov/cdap/actions/runs/17502758868/job/49719410970

---------

Co-authored-by: Maboh Christopher <chris.maboh@aquia.io>
# This is the commit message #6:

[PLT-1320] Update aws_backup_tag default in Aurora module (#298)

## 🎫 Ticket

https://jira.cms.gov/browse/PLT-1320

## 🛠 Changes

The default value for the aws_backup_tag in the Aurora module was
updated to the current version.

## ℹ️ Context

The aws_backup_tag changed and required an update in the Aurora module.

## 🧪 Validation

This is a trivial default value update.
# This is the commit message #7:

PR feedback

# This is the commit message #8:

PR feedback

# This is the commit message #9:

Update terraform/modules/ecs/cluster/main.tf

Co-authored-by: Sean Fern <seanfern@navapbc.com>
# This is the commit message #10:

PR feedback

# This is the commit message #11:

PR feedback

# This is the commit message #12:

pr feedback

# This is the commit message #13:

Update terraform/modules/ecs/cluster/outputs.tf

Co-authored-by: Michael J Burling <michael.burling@cms.hhs.gov>
# This is the commit message #14:

pr feedback

# This is the commit message #15:

apply usage

# This is the commit message #16:

apply usage

# This is the commit message #17:

PLT-1325: Add Prod env for opt out Lambdas for BCDA and DPC (#300)

## 🎫 Ticket

https://jira.cms.gov/browse/PLT-1325

## 🛠 Changes

prod env was added to bcda and dpc opt-out lambdas

## ℹ️ Context

prod environment had been removed for previous work around aurora
migration, with the work now done the is need to add the prod
environment to workflow back

<!-- If any of the following security implications apply, this PR must
not be merged without Stephen Walter's approval. Explain in this section
and add @SJWalter11 as a reviewer.
  - Adds a new software dependency or dependencies.
  - Modifies or invalidates one or more of our security controls.
  - Stores or transmits data that was not stored or transmitted before.
- Requires additional review of security implications for other reasons.
-->

## 🧪 Validation
See checks

---------

Co-authored-by: Maboh Christopher <chris.maboh@aquia.io>
# This is the commit message #18:

[PLT-1217] AWS Backups (#301)

## 🎫 Ticket

https://jira.cms.gov/browse/PLT-1217

## 🛠 Changes

added aws backup plan, vaults, policies

When applying we must import existing vaults:
terraform import aws_backup_vault.primary CMS_OIT_Backups_Vault
terraform import aws_backup_vault.secondary CMS_OIT_Backups_Vault

## ℹ️ Context

Cleaned up PR from #281.

- [x] 4hr1CA_d7_w35_m90 plan, adding cross-region to the 4hourly_1 rule.
Result: 6 4-hour backups, 7 daily, 5 weekly, and 3 monthly.
- [x] Create a service in the cdap repo to manage that backup plan in
each account.
- [x] Update terraform for each team to use the new backup plan and drop
any other snapshots from the database configuration. Current selection
is an example that selects clusters by app-env name AND for tag: Backup
= cdap-managed. **We should refine how we plan to select resources to be
backed up.**
- [x] Per Michael Burling, create a vault for each ADO in both test and
prod.
- [x] Per Sean Fern, Create mirror vaults for each ADO in us-west-2. The
mirror vault names in secondary have a suffix "_cr". This is for
uniqueness so that vault locks apply correctly.
- [x] Per Michael Burling, Each vault should use the same key as the
database being backed up.
- [x] Per Michael Burling, Add a lock to each Vault configured like the
CMS_OIT vault.
- [x] Per Sean Fern, we are using the role:
arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/delegatedadmin/developer/**cms-oit-aws-backup-service-role**

## 🧪 Validation

See checks - tf-backup-plan workflow.

---------

Co-authored-by: Michael J Burling <michael.burling@cms.hhs.gov>
Co-authored-by: Sean Fern <seanfern@navapbc.com>
# This is the commit message #19:

formatting

# This is the commit message #20:

formatting

# This is the commit message #21:

refactors

# This is the commit message #22:

ONE HASH

# This is the commit message #23:

Initial checkin for ecs service module.

# This is the commit message #24:

ecs service and task def with inputs

# This is the commit message #25:

Revert "ONE HASH"

This reverts commit e42759767468b0cced22739fb95d1cf843529be5.